#!/bin/sh                                                         \\//Enter Token, UserName and RepoName before use\\//                                                                                      
Token=$(echo "[Token]");
UserName=$(echo "[User Name]");
RepoName=$(echo "[Repository name]");
git add $1;
git commit -m \"$2\";
git push https://$Token@github.com/$UserName/$RepoName.git;
